name: AutoDocGPT

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use AutoDocGPT
        uses: morepriyam/autodocgpt@main
        with:
          email: ${{ github.actor }}@users.noreply.github.com
          name: ${{ github.actor }}
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
