name: Test README Generation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run README generation action
        uses: ./ # Use the local action in your repository
        with:
          email: testuser@example.com
          name: Test User
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
